# Generated by Django 3.2.15 on 2022-09-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_auto_20220927_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.CharField(choices=[('', '予約日'), ('1', '6/1'), ('2', '6/2'), ('3', '6/3')], error_messages={'required': '必須！'}, max_length=20, verbose_name='予約日'),
        ),
    ]
