# Generated by Django 3.2.15 on 2022-09-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_alter_reserve_reserve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='comment',
            field=models.TextField(error_messages={'required': False}, max_length=254, verbose_name='備考欄'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.CharField(choices=[('', '予約日'), ('1', '6/1'), ('2', '6/2'), ('3', '6/3')], max_length=20, verbose_name='予約日'),
        ),
    ]
