# Generated by Django 3.2.15 on 2022-09-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_auto_20220928_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='comment',
            field=models.TextField(max_length=254, null=True, verbose_name='備考欄'),
        ),
    ]
