# Generated by Django 3.2.15 on 2022-09-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0008_alter_reserve_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='comment',
            field=models.TextField(blank=True, max_length=254, null=True, verbose_name='備考欄'),
        ),
    ]
