# Generated by Django 3.2.15 on 2022-09-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0013_auto_20220928_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='name',
            field=models.CharField(max_length=20, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='tel',
            field=models.CharField(max_length=15, verbose_name='電話番号'),
        ),
    ]
