# Generated by Django 3.2.15 on 2022-09-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0014_auto_20220929_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='電話番号'),
        ),
    ]
