# Generated by Django 3.2.15 on 2022-09-29 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0016_alter_reserve_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='tel',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='「例：080-1234-5678」のように入力してください。', regex='?P<電話>0[789]0-\\d{4}-\\d{4}')], verbose_name='電話番号'),
        ),
    ]
