# Generated by Django 3.2.15 on 2022-09-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0018_alter_reserve_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.CharField(choices=[('', '予約日'), ('20220601', '6/1'), ('20220602', '6/2'), ('20220603', '6/3')], max_length=20, verbose_name='予約日'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_time',
            field=models.CharField(choices=[('', '予約時間'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00')], max_length=10, verbose_name='予約時間'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='reservable_date',
            field=models.DateTimeField(verbose_name='予約可能日'),
        ),
    ]
