# Generated by Django 3.2.15 on 2022-09-30 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0019_auto_20220930_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.shop', verbose_name='予約日'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_num',
            field=models.CharField(max_length=10, verbose_name='予約人数'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_time',
            field=models.CharField(max_length=10, verbose_name='予約時間'),
        ),
    ]
