# Generated by Django 3.2.15 on 2022-09-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0021_alter_reserve_reserve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.CharField(max_length=20, verbose_name='予約日'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='reservable_date',
            field=models.DateField(verbose_name='予約可能日'),
        ),
    ]
