# Generated by Django 3.2.15 on 2022-09-30 07:41

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0022_auto_20220930_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.CharField(choices=[(datetime.date(2022, 9, 30), datetime.date(2022, 9, 30))], max_length=20, verbose_name='予約日'),
        ),
    ]
