# Generated by Django 3.2.15 on 2022-09-30 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0023_alter_reserve_reserve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.DateField(choices=[('', '予約日')], max_length=20, unique=True, verbose_name='予約日'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_num',
            field=models.IntegerField(choices=[('', '予約人数')], unique=True, verbose_name='予約人数'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_time',
            field=models.TimeField(choices=[('', '予約時間')], max_length=10, unique=True, verbose_name='予約時間'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='tel',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='「例：080-1234-5678」のように入力してください。', regex='^0[789]0-\\d{4}-\\d{4}')], verbose_name='電話番号'),
        ),
    ]
