# Generated by Django 3.2.15 on 2022-10-01 03:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0024_auto_20220930_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.DateField(choices=[('', '予約日'), ('10/01', '10/01'), ('10/02', '10/02'), ('10/03', '10/03'), ('10/04', '10/04'), ('10/05', '10/05'), ('10/06', '10/06'), ('10/07', '10/07')], max_length=20, unique=True, verbose_name='予約日'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_num',
            field=models.IntegerField(choices=[('', '予約人数'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], unique=True, verbose_name='予約人数'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_time',
            field=models.TimeField(choices=[('', '予約時間'), (datetime.time(17, 0), datetime.time(17, 0)), (datetime.time(18, 0), datetime.time(18, 0)), (datetime.time(19, 0), datetime.time(19, 0)), (datetime.time(20, 0), datetime.time(20, 0)), (datetime.time(21, 0), datetime.time(21, 0))], max_length=10, unique=True, verbose_name='予約時間'),
        ),
    ]
