# Generated by Django 3.2.15 on 2022-10-01 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0026_auto_20221001_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='email',
            field=models.EmailField(error_messages={'unique': 'こちらのメールアドレスで既にご予約がされています。'}, max_length=100, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='tel',
            field=models.CharField(error_messages={'unique': 'こちらの電話番号で既にご予約がされています。'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='「例：080-1234-5678」のように入力してください。', regex='^0[789]0-\\d{4}-\\d{4}')], verbose_name='電話番号'),
        ),
    ]
