# Generated by Django 3.2.15 on 2022-10-05 04:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0026_auto_20221001_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=20, verbose_name='設定ネーム')),
            ],
        ),
        migrations.AlterField(
            model_name='reserve',
            name='email',
            field=models.EmailField(error_messages={'unique': 'こちらのメールアドレスで既にご予約がされています。'}, max_length=100, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.DateField(choices=[('', '予約日'), (datetime.date(2022, 9, 28), datetime.date(2022, 9, 28)), (datetime.date(2022, 9, 29), datetime.date(2022, 9, 29)), (datetime.date(2022, 9, 30), datetime.date(2022, 9, 30)), (datetime.date(2022, 10, 1), datetime.date(2022, 10, 1)), (datetime.date(2022, 10, 2), datetime.date(2022, 10, 2)), (datetime.date(2022, 10, 3), datetime.date(2022, 10, 3)), (datetime.date(2022, 10, 4), datetime.date(2022, 10, 4))], max_length=20, verbose_name='予約日'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_time',
            field=models.TimeField(choices=[('', '予約時間'), (datetime.time(17, 0), datetime.time(17, 0)), (datetime.time(18, 0), datetime.time(18, 0)), (datetime.time(19, 0), datetime.time(19, 0)), (datetime.time(20, 0), datetime.time(20, 0)), (datetime.time(21, 0), datetime.time(21, 0))], max_length=10, verbose_name='予約時間'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='tel',
            field=models.CharField(error_messages={'unique': 'こちらの電話番号で既にご予約がされています。'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='「例：080-1234-5678」のように入力してください。', regex='^0[789]0-\\d{4}-\\d{4}')], verbose_name='電話番号'),
        ),
        migrations.CreateModel(
            name='StartTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.setintegration', verbose_name='設定ネーム')),
            ],
        ),
        migrations.CreateModel(
            name='ReservableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservable_date', models.CharField(max_length=10, verbose_name='予約可能時間')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.setintegration', verbose_name='設定ネーム')),
            ],
        ),
        migrations.CreateModel(
            name='MaxReserveNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_reserve_num', models.IntegerField(verbose_name='予約上限人数')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.setintegration', verbose_name='設定ネーム')),
            ],
        ),
        migrations.CreateModel(
            name='EndTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.setintegration', verbose_name='設定ネーム')),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='end_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.endtime', verbose_name='閉店時間'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='max_reserve_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.maxreservenum', verbose_name='１時間当たりの予約上限人数'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='reservable_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reserve.reservabledate', verbose_name='予約可能日'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='start_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.starttime', verbose_name='開店時間'),
        ),
    ]
