# Generated by Django 3.2.15 on 2022-10-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0027_auto_20221001_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='max_reserve_num',
            field=models.IntegerField(default=10, verbose_name='１時間当たりの予約上限人数'),
        ),
    ]
