# Generated by Django 3.2.15 on 2022-10-01 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0028_alter_shop_max_reserve_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_time',
            field=models.TimeField(choices=[('', '予約時間'), (datetime.time(17, 0), datetime.time(17, 0)), (datetime.time(18, 0), datetime.time(18, 0)), (datetime.time(19, 0), datetime.time(19, 0)), (datetime.time(20, 0), datetime.time(20, 0)), (datetime.time(21, 0), datetime.time(21, 0))], max_length=10, verbose_name='予約時間'),
        ),
    ]
