# Generated by Django 3.2.15 on 2022-10-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0029_auto_20221007_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.DateField(choices=[('', '予約日'), ('1', '2022-10-10')], max_length=20, verbose_name='予約日'),
        ),
    ]
