# Generated by Django 3.2.15 on 2022-10-02 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0029_alter_reserve_reserve_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.DateField(choices=[('', '予約日'), (datetime.date(2022, 10, 2), datetime.date(2022, 10, 2)), (datetime.date(2022, 10, 3), datetime.date(2022, 10, 3)), (datetime.date(2022, 10, 4), datetime.date(2022, 10, 4)), (datetime.date(2022, 10, 5), datetime.date(2022, 10, 5)), (datetime.date(2022, 10, 6), datetime.date(2022, 10, 6)), (datetime.date(2022, 10, 7), datetime.date(2022, 10, 7)), (datetime.date(2022, 10, 8), datetime.date(2022, 10, 8))], max_length=20, verbose_name='予約日'),
        ),
    ]
