# Generated by Django 3.2.15 on 2022-10-02 03:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0030_alter_reserve_reserve_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='reservable_date',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.DateField(choices=[('', '予約日'), (datetime.date(2022, 9, 28), datetime.date(2022, 9, 28)), (datetime.date(2022, 9, 29), datetime.date(2022, 9, 29)), (datetime.date(2022, 9, 30), datetime.date(2022, 9, 30)), (datetime.date(2022, 10, 1), datetime.date(2022, 10, 1)), (datetime.date(2022, 10, 2), datetime.date(2022, 10, 2)), (datetime.date(2022, 10, 3), datetime.date(2022, 10, 3)), (datetime.date(2022, 10, 4), datetime.date(2022, 10, 4))], max_length=20, verbose_name='予約日'),
        ),
        migrations.CreateModel(
            name='ReservableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservable_date', models.DateField(verbose_name='予約可能時間')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.shop')),
            ],
        ),
    ]
