# Generated by Django 3.2.15 on 2022-10-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0031_alter_reserve_reserve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.DateField(max_length=20, verbose_name='予約日'),
        ),
    ]
